version: '3.7'
services:
  mongodb_container:
    image: mongo
    env_file:
      - .env
    ports:
      - 27017:27017
    volumes:
      - ./db_dev:/data/db


#docker-compose up -d
#mongo admin -u root -p rootpassword