name: build-frontend
on:
  push:
    paths:
    - "backend/**"
    - ".github/workflows/build-backend.yml"
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: '15'
      - name: Install modules
        run: npm install
      - name: Unit test back
        run: npm run test:backend