name: tests-recipes

on:
  pull_request:
    paths:
      - 'recipes/**'
  push:
    branches:
      - dev
    paths:
      - 'recipes/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd recipes && npm install && npm run test:ci
